// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManagement.Repositories;

#nullable disable

namespace StockManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250626173256_seedData2")]
    partial class seedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StockManagement.Dtos.InventoryStatementDto", b =>
                {
                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InboundQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutboundQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("StockBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("InventoryStatement");
                });

            modelBuilder.Entity("StockManagement.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentNumber = "GIR-K001",
                            ProductId = 1,
                            Quantity = 100m,
                            TransactionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 2,
                            DocumentNumber = "CIK-K001",
                            ProductId = 1,
                            Quantity = 20m,
                            TransactionDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 3,
                            DocumentNumber = "GIR-K002",
                            ProductId = 1,
                            Quantity = 50m,
                            TransactionDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 4,
                            DocumentNumber = "CIK-K002",
                            ProductId = 1,
                            Quantity = 30m,
                            TransactionDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 5,
                            DocumentNumber = "GIR-K003",
                            ProductId = 1,
                            Quantity = 70m,
                            TransactionDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 6,
                            DocumentNumber = "GIR-D001",
                            ProductId = 2,
                            Quantity = 120m,
                            TransactionDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 7,
                            DocumentNumber = "CIK-D001",
                            ProductId = 2,
                            Quantity = 25m,
                            TransactionDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 8,
                            DocumentNumber = "GIR-D002",
                            ProductId = 2,
                            Quantity = 80m,
                            TransactionDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 9,
                            DocumentNumber = "CIK-D002",
                            ProductId = 2,
                            Quantity = 40m,
                            TransactionDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 10,
                            DocumentNumber = "GIR-D003",
                            ProductId = 2,
                            Quantity = 100m,
                            TransactionDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 11,
                            DocumentNumber = "GIR-S001",
                            ProductId = 3,
                            Quantity = 90m,
                            TransactionDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 12,
                            DocumentNumber = "CIK-S001",
                            ProductId = 3,
                            Quantity = 15m,
                            TransactionDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 13,
                            DocumentNumber = "GIR-S002",
                            ProductId = 3,
                            Quantity = 60m,
                            TransactionDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 14,
                            DocumentNumber = "CIK-S002",
                            ProductId = 3,
                            Quantity = 25m,
                            TransactionDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 15,
                            DocumentNumber = "GIR-S003",
                            ProductId = 3,
                            Quantity = 110m,
                            TransactionDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("StockManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kalem",
                            ProductCode = "P001",
                            Unit = "Adet",
                            VatRate = 8m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Defter",
                            ProductCode = "P002",
                            Unit = "Adet",
                            VatRate = 18m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Silgi",
                            ProductCode = "P003",
                            Unit = "Adet",
                            VatRate = 8m
                        });
                });

            modelBuilder.Entity("StockManagement.Models.InventoryTransaction", b =>
                {
                    b.HasOne("StockManagement.Models.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockManagement.Models.Product", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
